### ISSUE TITLE
Custom User models

### ISSUE THREAD

**Issue by bashu** [edoburu/fluentcms-emailtemplates#1]
``` python
Traceback (most recent call last):
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/wsgiref/handlers.py", line 85, in run
    self.result = application(self.environ, self.start_response)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/staticfiles/handlers.py", line 64, in __call__
    return self.application(environ, start_response)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/core/handlers/wsgi.py", line 187, in __call__
    response = self.get_response(request)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/core/handlers/base.py", line 199, in get_response
    response = self.handle_uncaught_exception(request, resolver, sys.exc_info())
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/core/handlers/base.py", line 111, in get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/decorators.py", line 105, in _wrapped_view
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/views/decorators/cache.py", line 52, in _wrapped_view_func
    response = view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/admin/sites.py", line 206, in inner
    return view(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/views/generic/base.py", line 69, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/decorators.py", line 29, in _wrapper
    return bound_func(*args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/contrib/auth/decorators.py", line 21, in _wrapped_view
    return view_func(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/decorators.py", line 25, in bound_func
    return func.__get__(self, type(self))(*args2, **kwargs2)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/fluentcms_emailtemplates/views.py", line 18, in dispatch
    return super(StaffMemberRequiredMixin, self).dispatch(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/views/generic/base.py", line 87, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/views/generic/detail.py", line 115, in get
    context = self.get_context_data(object=self.object)
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/fluentcms_emailtemplates/views.py", line 33, in get_context_data
    user=self.request.user,
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/fluentcms_emailtemplates/rendering.py", line 176, in render_email_template
    'first_name': context_user.first_name if context_user else '',
  File "/Users/bashu/.virtualenvs/ifacca/lib/python2.7/site-packages/django/utils/functional.py", line 225, in inner
    return func(self._wrapped, *args)
AttributeError: 'User' object has no attribute 'first_name'
```

**Comment by bashu** [comment]
nevermind, I have fixed by adding first_name, last_name properties
